### ISSUE TITLE
mmap2_threads takes extremly long time to create threads on 256 cores macine

### ISSUE THREAD

**Issue by aaronlu** [antonblanchard/will-it-scale#4]
Hi Anton,
I recently found the mmap2_threads test couldn't finish in a reasonable time on a 256 cores machine. Investigation revealed that the main thread is contending severely with the spawned threads on the single mm->mmap_sem. The reason is the main thread needs also to do mmap() due to things like malloc() for task's argument, etc.

To make the main thread proceed properly, I have a patch to let all spawned tasks/threads wait for an event from main thread that is only delivered after task/thread creation is done. What do you think of this patch, is it worth? Thanks.

https://github.com/aaronlu/will-it-scale/commit/7f0b4fb409fd3e8aae32761211b43e2b947f051a

**Comment by antonblanchard** [comment]
Hi Aaron, looks good to me. Thanks!
