### ISSUE TITLE
NetBSD port request

### ISSUE THREAD

**Issue by krytarowski** [antonblanchard/will-it-scale#7]
I've been suggested to verify the NetBSD system with this renowned tool. What are the plans for a NetBSD port?

**Comment by krytarowski** [comment]
I've prepared a scratch port in pkgsrc:

https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=commitdiff;h=d534c166e018ba921598e9a58e43a37325b2635a;hp=a0441d5608369c1389c73a35cb5cb05739654331

**Comment by mjoras** [comment]
I've done something a bit different for the task affinity, using hwloc directly: https://github.com/antonblanchard/will-it-scale/pull/8

**Comment by krytarowski** [comment]
Looks good!

**Comment by mjoras** [comment]
If I'm feeling motivated and that gets merged I may also make a FreeBSD port for it.

**Comment by krytarowski** [comment]
It looks like we will be down to patching tests.

**Comment by antonblanchard** [comment]
Solved by https://github.com/antonblanchard/will-it-scale/pull/12

**Comment by krytarowski** [comment]
Opps, I totally missed this activity. It works now better, I have now other patches to build on NetBSD.
